title: Son Thanh Pham (Sony)
logo: "https://github.com/sonphamily/sonypham.github.io/blob/main/images/profilepicture.jpeg"
description: Data Analyst
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
